baseURL = 'https://www.cybertheye.com/braindump/'
languageCode = 'en-us'
title = "Cyven's Braindump"
theme='cortex'
#staticDir=''
#theme='ananke'
#canonifyURLs=true
relativeURLs=false
[caches]
  [caches.images]
    dir = ':cacheDir/images'
